name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: set version to stable
      run: rustup install stable
    - name: pandoc
      run: sudo apt-get install pandoc -y
    - name: install diesel cli
      run: cargo install diesel_cli
    - name: create a .secret
      run: openssl rand -base64 32 > .secret
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: diesel migration run
      run: diesel migration run
    - name: Run tests
      run: cargo test --verbose
